# Generated by Django 3.0.5 on 2021-02-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20210223_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='category',
            new_name='attributes',
        ),
    ]
