# Generated by Django 3.0.5 on 2021-02-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_auto_20210223_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_app.FoodCategory'),
        ),
    ]
