# Generated by Django 3.0.5 on 2021-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_fooditems_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
