# Generated by Django 3.0.5 on 2021-02-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_fooditems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
